### ISSUE TITLE
ParentNode - name clash with QPA package

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/francy#30]
After @sebasguts added Francy to the Docker container for the GAP master branch, package tests using that container all fail with the following:

    Error, operation` ParentNode' was created as an attribute, use `DeclareAttribute'

See e.g. https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/builds/392020023

Indeed, QPA does `DeclareOperation( "ParentNode", [IsSuffixTreeNode] );` and Francy does `DeclareAttribute("ParentNode", IsShape);` so it's not possible to load QPA after Francy. Could we resolve this in Francy as soon as possible please?

**Comment by mcmartins** [comment]
I've changed this to be `ParentShape` instead. It makes more sense taking in account the other objects... Checked loading all packages and nothing seems to clash anymore...
