### ISSUE TITLE
Weird overrides for SetSize etc.

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/francy#38]
We discovered that Francy installs methods for `SetSize` etc. and were wondering why. Looking closer, we discovered this code:
```
DeclareCategory("IsFrancyObject", IsObject);
...
DeclareCategory("IsShape", IsFrancyObject);
...
DeclareRepresentation("IsShapeRep", IsComponentObjectRep, [], IsShape);
...
DeclareAttribute("Size", IsShape);
InstallMethod(Size, "shape", [IsShape], o -> o!.size);
InstallMethod(SetSize, "shape, int", [IsShape, IsPosInt], function(o, i) o!.size := i; end);
```

This is quite puzzling to me, because it means that you are essentially reimplementing a core GAP feature: namely, attribute storing representations. As a matter of fact, if you remove your custom `Size` and `SetSize` methods, and replace `IsComponentObjectRep` by `IsAttributeStoringRep`, then you get almost identical code, except that `o!.size` becomes `o!.Size`.

Is there a reason you are not using `IsAttributeStoringRep`? If not, I'd strongly suggest to switch to it, else you code will be a very non-gapish oddball, hard to understand and debug for people who are used to working with "standard" GAP objects. At the same time, you should be able to delete a ton of methods this way.

**Comment by mcmartins** [comment]
Hi @fingolfin , thank you for your feedback.

Well, my explanation is simple. All the code in **francy** will be used to produce a `JSON` in the end, and to keep some formality about it, camel case is used across the whole schema. This makes it simple for the `JSON` validation and external use.

Using the suggested `IsAttributeStoringRep`, will end up with something that is not camel case, of course I could set the property to `DeclareAttribute("size", IsShape);` (lower case), but then it would make GAP code less consistent, as we would have instead `Setsize(shape, 20);` etc... 

Would this be an acceptable justification?

Manuel
