### ISSUE TITLE
Rename HelloWorld in the test

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/francy#39]
`HelloWorld` is defined as a function in the Example package, hence this test fails when all packages are loaded. Could you please rename it e.g. to `helloworld`? 

https://github.com/gap-packages/francy/blob/dbf0cc0a92ebadd9e38db938a0942d04455328ee/tst/menu.tst#L12

**Comment by mcmartins** [comment]
I've fixed this in master. @alex-konovalov are those tests pulling from master or from the release package?

**Comment by olexandr-konovalov** [comment]
Thanks. Tests which tests all three configurations (with/without/with default package) are using the official release. A quick minor release would be very timely.

**Comment by mcmartins** [comment]
Done - v1.0.4
