### ISSUE TITLE
Development installation

### ISSUE THREAD

**Issue by zerline** [gap-packages/francy#42]
Hi Manuel!

I've been trying to install jupyter_francy in development mode, but the JS files do not seem to get built. I have tried following commands (from ./js/packages/francy-extension-jupyter):

> $ pip install -vvv -e .
/.../
running egg_info
    writing jupyter_francy.egg-info/PKG-INFO
    writing dependency_links to jupyter_francy.egg-info/dependency_links.txt
    writing requirements to jupyter_francy.egg-info/requires.txt
    writing top-level names to jupyter_francy.egg-info/top_level.txt
    reading manifest file 'jupyter_francy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no directories found matching 'jupyter_francy/nbextension'
    warning: no directories found matching 'jupyter_francy/labextension'

> $ python setup.py egg_info
running egg_info
writing jupyter_francy.egg-info/PKG-INFO
writing dependency_links to jupyter_francy.egg-info/dependency_links.txt
writing requirements to jupyter_francy.egg-info/requires.txt
writing top-level names to jupyter_francy.egg-info/top_level.txt
reading manifest file 'jupyter_francy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'jupyter_francy/nbextension'
warning: no directories found matching 'jupyter_francy/labextension'
writing manifest file 'jupyter_francy.egg-info/SOURCES.txt'

>  $ python setup.py sdist
-> no JS files at all in the resulting .tar.gz

**Comment by mcmartins** [comment]
Hi Odile,

I think there are some steps missing before you can do `pip install -vvv -e .`

The following steps can be retrieved from the travis scripts `https://github.com/gap-packages/francy/blob/master/scripts/prepare.sh` and need to be executed before the pip install:
```
user@local $> cd francy/js
user@local $> npm install
user@local $> npm run bootstrap
user@local $> npm run build
user@local $> cd packages/francy-extension-jupyter
user@local $> pip install -vvv -e .
```
I'll update the documentation to include the steps for building from source in development mode, as the ones currently mentioned in the documentation are for end users.

Let me know.

Manuel

**Comment by zerline** [comment]
Thanks.
Now I have some editable JS Francy files!

**Comment by zerline** [comment]
IMHO your unique command line in "lab.README.md" (*) should be added to the general README.md 

(*)  jupyter labextension install jupyter-francy

**Comment by zerline** [comment]
> I think there are some steps missing before you can do `pip install -vvv -e .`

Hi Manuel!

Those steps should probably be integrated into the jupyter extension setup.py. I'll have a look at it.
