### ISSUE TITLE
francy-widget for Jupyterlab does not work

### ISSUE THREAD

**Issue by zerline** [gap-packages/francy#44]
My own `francy-widget` depends on `francy` for all javascript and does not work on Jupyterlab: the browser does not seem to find the JS code, there is an error about not finding a file, although I can open the file from that same path.

I've been told that it comes from an incomplete javascript installation of francy.

I'll add more details later.

**Comment by zerline** [comment]
I just started re-writing the jupyter extension installation process, for it seems outdated. Not yet ready though, it needs more testing.
BTW do you mind if do that?

**Comment by mcmartins** [comment]
If you update it and make it work, I’ll be happy to accept a pull request for this ;)

**Comment by zerline** [comment]
Hi Manuel
I've spent some time on this new installation procedure, see https://github.com/zerline/francy/tree/issue%2344/js/packages/francy-extension-jupyter.

- It does the job except for the "vendor" part, for which `npm run build:nbextension` returns an error 
```
ERROR in ./node_modules/francy-core/index.js
    Module not found: Error: Can't resolve 'seedrandom' in '/home/odile/prj/francy.my/js/packages/francy-extension-jupyter/node_modules/francy-core'
     @ ./node_modules/francy-core/index.js 25:0-51 25:0-51
     @ ./node_modules/francy-renderer-d3/index.js
     @ ./src/lab_extension.js
     @ multi babel-polyfill ./src/lab_extension.js

```
- I've done my best to upgrade the dependencies list, with a few "fuzzy" decisions ..

Hope it'll help ..

**Comment by mcmartins** [comment]
Removed the jupyter notebook package and will support only JupyterLab. 
The code was refactored to align with the latest jupyterlab extension guidelines.
