### ISSUE TITLE
Modal menus subject to bugs

### ISSUE THREAD

**Issue by zerline** [gap-packages/francy#45]
Currently, I'm unable to get any graph node modal menus on the Jupyter notebook with a Python kernel. This regression happened after a development installation. Previously, I had them. I'll check again and add more details here.

Moreover on Jupyterlab, right clicking opens a specific Jupyterlab context menu. See https://github.com/jupyterlab/jupyterlab/issues/3521

**Comment by mcmartins** [comment]
Humm, I’ve always thought you had to press SHIFT and then right click to see custom menus on jupyterlab... need to investigate this further...

**Comment by zerline** [comment]
It's possibly a regression. Last time I tried, SHIFT-right-click would replace the Jupyterlab context menu by .. the browser context menu.

**Comment by mcmartins** [comment]
Fixed on #88
