### ISSUE TITLE
Merging zerline/francy-widget

### ISSUE THREAD

**Issue by zerline** [gap-packages/francy#47]
Hi Manuel

Do you think we could merge my `francy-widget` into  `francy` as a subpackage?

If so, do you have specifications for me before I attempt a PR?

Best,

**Comment by mcmartins** [comment]
Hi @zerline, yes we can merge your code as a subpackage of francy... I'm having my PhD viva next week, so I'm a bit busy these days, but I'll be happy to support this on the upcoming weeks :)

**Comment by mcmartins** [comment]
I'm not going to merge this for the next release, but will have a few things in consideration.
