### ISSUE TITLE
messages on canvas not removable

### ISSUE THREAD

**Issue by chpech** [gap-packages/francy#49]
Hi Manuel,
I am implementing an interface for coco2p to francy and came upon a problem when removing messages using a callback. I attached a minimal example for the explanation:

[tstfrancymsg.g.gz](https://github.com/gap-packages/francy/files/4460939/tstfrancymsg.g.gz)

- When adding msg1 and immediately removing it, it remains on the screen.
- When adding msg1 and msg2 and then removing msg1 the msg1 is removed. Trying to remove msg2 afterwards remains unsuccessful.
- When adding msg1 and msg2 and the remove both at once, nothing happens
- When adding msg1 and remove it and the add msg2, then msg2 overwrites msg1

It seems that francy is not always redrawing the screen when removing a message.

Best,
Christian

**Comment by mcmartins** [comment]
Hi Christian,

I remember doing something hacky to handle messages, because the communication between the frontend and the kernel is not fully duplex. I mean, when a user click to close a message dialog, it does not propagate to the kernel, hence when it gets rendered again in the browser D3 will have the previous state and not render it again (I think this was the design I chose). 

I'll replicate with you instructions and try to fix accordingly.

Thanks for your feedback!

Manuel

**Comment by chpech** [comment]
Dear Manuel,

thank you very much for your quick reaction. Just to clarify perhaps a bit more, what I try to achieve: I would like that one callback opens a series of messages and another callback removes these messages once more. The user may or may not choose to close one or another message herself, but this is not of concern to the package. The trouble is, when the second callback removes all messages that it knows of (and these are usually all messages), then the messages get removed on the gap-side, but not on the screen. If the callback removes just one message from several, then the message vanishes also from the screen. It seems that only when it tries to remove all messages, then no redraw happens.

Once more, thank you for looking into this.

Best regards,
Christian

--

**Comment by mcmartins** [comment]
I'll try to look into this for the next release.

**Comment by mcmartins** [comment]
Fixed all the bugs reported on this issue plus implemented a close message callback for all messages created (when a message is closed on the GUI it will destroy it on gap as well).
