### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/francy#58]
@mcmartins there are several PRs from dependabot - perhaps a time for a new release, to include into the forthcoming GAP release?

**Comment by mcmartins** [comment]
I'll try to prepare a new release, cannot promise on a specific that.
It will imply changing the jupyterlab extension to work with the new jupyterlab 3, and some packages require lots of changes on the javascript rendering side as well.

**Comment by olexandr-konovalov** [comment]
Would be nice. There is a bunch of PRs from dependabot...

**Comment by olexandr-konovalov** [comment]
> It will imply changing the jupyterlab extension to work with the new jupyterlab 3, and some packages require lots of changes on the javascript rendering side as well.

@mcmartins Could you post some more details about work to be done - maybe someone will be interested to help.

#68 switches from Travis CI to GitHub Actions - hope that will help to test those PRs.

**Comment by mcmartins** [comment]
Sure, that would preferable actually, and I could provide guidance in that case.

The CVE reports are not for direct dependencies of Francy, and those might be or not updated on the latest version of Francys' dependencies .

In terms of tasks (work on `develop`):

- It is needed to update `js/package.json` to include the latest dependencies
-- It might be needed to update the JavaScript code where these dependencies are used to match the code changes
- It is needed to review the JupyterLab/JupyterNotebook extensions to make sure they work on the latest version of Jupyter
-- Some work is already done on the `francy-widget` branch
- Make sure everything works fine, there are plenty of tests and test notebooks
- Some of the issues reported here are easy fix as well, so they could be included

**Comment by olexandr-konovalov** [comment]
Thanks @mcmartins - pinging @ZachNewbery to bring it to his attention!

**Comment by mcmartins** [comment]
I've released a new version after a few attempts... will release a minor version in the next days with a few fixes on the binder image and some minor changes on the CICD workflows
