### ISSUE TITLE
Problem with "open" on Debian/Ubuntu et al

### ISSUE THREAD

**Issue by frankluebeck** [gap-packages/francy#59]
On my Debian and Ubuntu systems the test file `francy-1.2.4 /tst/canvas.tst` runs into an error at the command  `DrawSplash(canvas);`. The reason is that the corresponding method tries to open an HTML file in my standard browser with the command `open`. But on my system `/bin/open` is a link to `openvt`, while I guess you want to call the program called `xdg-open` which would open a local html-file in my preferred browser.

Unfortunately, I don't know if changing `open` to `xdg-open` in your code would work on most Linux systems.

**Comment by mcmartins** [comment]
Thanks @frankluebeck.
I believe `xdg-open` shall be used instead of `open`, that is most likely just a link to either `xdg-open` or another tool e.g. `openvt`. None of them will work on every unix system, though, the right command is indeed `xdg-open`.
I'll include this in a future release.

**Comment by mcmartins** [comment]
A bit late, but will go into the next release - Pull Request #88.
