### ISSUE TITLE
minimize intersections of lables in .HASSE

### ISSUE THREAD

**Issue by pedritomelenas** [gap-packages/francy#9]
It should be nice to have a way to minimize intersections of edges. This is interesting when drawing Hasse diagrams. Graphviz has this possibility, but with d3 this can be somehow difficult to achieve.
Thanks,
Pedro

**Comment by mcmartins** [comment]
Hi Pedro, I'll take a look into this ASAP... I'll probably create a fork of Francy d3 and implement it with viz.js

**Comment by pedritomelenas** [comment]
Manuel,
Will you be able to get callbacks with viz.js?
Thanks,
Pedro

**Comment by mcmartins** [comment]
Ok, going back to this.
I won't implement a fork of this with viz.js.
I wouldn't like to use more dependencies on the project, but the truth is that in large structures it might become a mess if we don't use a strategy to position labels...
I'll look into something like: 
- https://bl.ocks.org/ColinEberhardt/389c76c6a544af9f0cab

**Comment by mcmartins** [comment]
Released v0.5.2

**Comment by pedritomelenas** [comment]
Probably instead of moving vertically to avoid overlaps, you could spread horizontally the edges. As it is now
<img width="766" alt="captura de pantalla 2018-03-04 a las 11 28 18" src="https://user-images.githubusercontent.com/9551023/36944554-44721d24-1f9f-11e8-8589-0d8bbe3c3ce6.png">
it seems that some edges in the same "level" are in different ones.
