### ISSUE TITLE
Canvas test failures

### ISSUE THREAD

**Issue by jamesjer** [gap-packages/francy#91]
The tests in the 2.0.0 release fail in canvas.tst, because the string returned by `FrancyId(canvas)` does not match the expected value.  The same is true for the `id` field in the output of `PrintObj(canvas)`.  If I am reading the code correctly, the ID is a random uuid prepended with `F`.  This means that test is very nearly guaranteed to fail.

**Comment by jamesjer** [comment]
This also affects the output of `GetLinks(graph);` in graph.tst.

**Comment by mcmartins** [comment]
That's true, the ID are uuids. The weird thing is that locally and on the github actions the tests were passing, e.g.: https://github.com/gap-packages/francy/actions/runs/4237207803/jobs/7363113640

I've added `gap> RANDOM_SEED(1);` on all tests in the develop branch (which I believe should do the trick).

**Comment by jamesjer** [comment]
That's interesting.  I see that if I run the tests multiple times, I get the same ID in each run.  But if I completely remove the buildroot and spin up a new one, I get a different ID, which also persists across multiple tests.  Does that mean that the random number generator is given a predictable seed?  If so, then `RANDOM_SEED(1)` should indeed do the trick.

**Comment by mcmartins** [comment]
Yes, that should do the trick if the tests are ran on the same "session".
Though, for the system packages release tests run twice which then fails, see [comment on #92](https://github.com/gap-packages/francy/issues/92#issuecomment-1469928460)
I've removed the offending test cases.
