### ISSUE TITLE
Strange `release.txt` file, also `RELEASE.md`?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/francy#93]
There is a file `release.txt` which says this:

> This major release includes multiple bug fixes and performance improvements.
> 
> We dropped support to jupyter notebooks extension.

So it looks as if this meant to be a kind of NEWS or CHANGES file. But then it should at the very least indicate which version it refers to (I'd suggest to also include the date that release was made).

At the same time there is a file `RELEASE.md` which despite its similar name seems to be totally unrelated, and serves as a reminder for @mcmartins . I would recommend to move that into a subdir `dev` or `etc`, and exclude it from the release tarball.

**Comment by mcmartins** [comment]
Indeed, RELEASE.md was an old document used to describe the old release procedure that was relying on Travis to run all the steps. I'll remove it.
The release.txt is used by the job softprops/action-gh-release@v1 and serves as the github release body text.
I'll exclude these form the tarball

**Comment by mcmartins** [comment]
I've removed both files
